version: '3.7'

services:
  # The application
  app:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./taskmanager:/taskmanager
    env_file:
      - .env.dev
    command: >
      sh -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  # Database
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=db_name
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_pass
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "7777:7777"
