# Generated by Django 4.0.2 on 2022-03-18 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='parent_stage_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_user.stage'),
        ),
    ]
