# Generated by Django 4.0.2 on 2022-03-19 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0003_alter_stage_parent_stage_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicwork',
            name='teacher_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_user.teacher'),
        ),
    ]
