# Generated by Django 4.0.2 on 2022-03-23 18:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0004_academicwork_teacher_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameTemplate',
            fields=[
                ('template_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_user.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='stage',
            name='actually_date',
            field=models.DateField(default=datetime.datetime.today, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='is_pass',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stage',
            name='planned_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='approach',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.CreateModel(
            name='TemplateStage',
            fields=[
                ('stage_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('duration', models.IntegerField(default=30)),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_user.templatestage')),
                ('template_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_user.nametemplate')),
            ],
        ),
    ]
